### PR TITLE
Add support of Berkeley DB 6.x.

### PR DESCRIPTION
**Pull request by yasuhirokimura**
Add support of Berkeley DB 6.x.

### CODE REVIEW

**Comment by hsbt** [comment]
@yasuhirokimura Thanks, I will merge this and fixed compatibility error with Travis CI with Ruby 2.5+.

**Comment by hsbt** [comment]
@yasuhirokimura Can you confirm to build with db6 and current master (https://github.com/ruby/dbm/commit/18da9b1c4248b2b92046bd7150a08ee645d63a50)?

After that, I will release 1.1.0 and merge to the ruby core repository.

**Comment by yasuhirokimura** [comment]
@hsbt I'm beginner about gem development and don't know how to test gem.
I made pull request as ruby/ruby#1918 at first but was suggested to request here.
So I tested it as modification of ruby core but didn't as ruby gem.
Would you please give me some pointer about how to test ruby gem?

**Comment by hsbt** [comment]
ok. I've test it and merge ruby core repository at https://github.com/ruby/ruby/commit/9e5cd30bc1b6440de529946135660808b1688302

**Pull request merged**
