### PR TITLE
Update dbm.gemspec

### PR DESCRIPTION
**Pull request by dsisnero**
update dbm for windows installer msys2 so that it downloads dbm dependencies

### CODE REVIEW

**Comment by gigacee** [comment]
I am very troubled with this problem, so I hope this PR will be marged as soon as possible.

**Comment by hsbt** [comment]
I'm not sure what is `msys2_mingw_dependencies`. Can anyone show the specification of `msys2_mingw_dependencies`?

**Comment by dsisnero** [comment]
https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers

RubyInstaller2 allows to define dependent MSYS2 packages in the gemspec
which are required for installation of the gem. The gem can then link to
libraries of this package or make use of commands provided by the package.
Both MINGW and MSYS2 packages can be specified, although only MINGW
packages are usable as library to link to.

MSYS2 packages can be specified per gemspec.metadata['msys2_dependencies'].
MINGW packages can be specified per
gemspec.metadata['msys2_mingw_dependencies']. The MINGW architecture is set
at install time according to the architecture of the running ruby process.
Therefore only the architecture independent part of the package name is
expected - the prefix mingw-w64-i686- and mingw-w64-x86_64- must be omitted.

Examples:

gemspec.metadata['msys2_mingw_dependencies'] = 'libusb sqlite'

Optionally the name can be followed by a version restriction as described
in the pacman man page <https://www.archlinux.org/pacman/pacman.8.html>:

gemspec.metadata['msys2_mingw_dependencies'] = 'libusb>=1.0.21'

However keep in mind that MSYS2 usually provides only one version at the
same time for each package.

MSYS2 package dependencies are installed per pacman command, when a gem is
about to be installed. The extconf.rb within a gem can access the newly
installed MSYS2-MINGW libraries. If the package installation fails, the
output of pacman is printed to the console, but the gem installation
continues nevertheless. Insofar setting a MSYS2 dependency can make the
installation easier, but will not brake the gem installation in case of
somehow changed MSYS2 packages.

Installation of MSYS2/MINGW packages can be disabled per gem install
gemname.gem --ignore-dependencies .
Examples for dependency definition: sqlite3
<https://github.com/sparklemotion/sqlite3-ruby/pull/214/commits/ea4077023ff68987cc33dd1f449e35746edf1a3a>
, glut
<https://github.com/larskanis/glut/commit/32c7591458fda44b8a4141f77867ced9de8e8920>
, fxruby
<https://github.com/larskanis/fxruby/commit/233f61f51fdc9b60b08d9636017450c209b1c195>
, openssl
<https://github.com/ruby/openssl/commit/061549b23758ebcce71c503cd6b75899b1196cae>
, mysql2
<https://github.com/brianmario/mysql2/commit/a2fadb667cc0a05660c18a7a3e10baa675205af9>

**Comment by hsbt** [comment]
Got it. Thanks.

**Pull request merged**
